server:
  port: 14511
spring:
  application:
    name: provider-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://192.168.43.103:5555
    username: root
    password: root
  scan:
    base-packages: com.neoniou.provider.service.impl
  protocol:
    name: dubbo
    port: 15511