server:
  port: 14510
spring:
  application:
    name: consumer-serivce
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: consumer-serivce
  registry:
    address: nacos://192.168.43.103:5555
    username: root
    password: root